name: Java CI with Spring Boot

on:
  push:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Push Docker image to GitHub Packages
      run: |
        echo "${{ secrets.GH_WFLOW_DI }}" | docker login ghcr.io -u suriya-mca --password-stdin
        docker build . -t ghcr.io/suriya-mca/geo:v0.0.1
        docker push ghcr.io/suriya-mca/geo:v0.0.1